### ISSUE TITLE
CobaltStrike 4.6 must be installed manually 

### ISSUE THREAD

**Issue by m1j09830** [cisagov/ansible-role-cobalt-strike#65]
# 💡 Summary #

CobaltStrike 4.6 has recently come out and will require the new package be downloaded from their website directly. Every subsequent update can follow the same process that is currently used (utilizing the update binary located in the /opt/cobaltstrike folder on the Kali and TeamServer images). 

## Motivation and context ##

If we don't pull the latest version of CobaltStrike directly from their website for 4.6 we will be unable to continue to use the latest features of CobaltStrike moving forward. 

## Implementation notes ##

Please see the following blog which further outlines why this is necessary (https://www.cobaltstrike.com/blog/cobalt-strike-4-6-the-line-in-the-sand/)

## Acceptance criteria ##

How do we know when this work is done?

- [ ] CobaltStrike 4.6 has been downloaded and installed on the Kali AMI
- [ ] CobaltStrike 4.6 has been downloaded and installed on the TeamServer AMI
- [ ] We can once again use the update binary located in the /opt/cobaltstrike directory to update future instances (This will be possible only after downloaded and installing CobaltStrike 4.6)

**Comment by mcdonnnj** [comment]
@m1j09830 Unless I am misreading this the release states that you cannot auto-update from 4.5 to 4.6 because the 4.5 updater is incompatible. This role is already designed to pull the distribution file from the CobaltStrike website and install it (if it does not already exist). That should make this a non-issue for this Ansible role, no?

**Comment by dav3r** [comment]
@jsf9k - Can you please take a look at this issue?  It looks like our download process needs to be modified as a result of these recent changes: https://github.com/cisagov/ansible-role-cobalt-strike/runs/6129714952?check_suite_focus=true#step:7:434.

**Comment by dav3r** [comment]
@m1j09830 Is your concern here about upgrading existing CS installations from 4.5 to 4.6?  Or are you trying to ensure that our next TeamServer AMI includes CS 4.6?

**Comment by m1j09830** [comment]
My apologies for the delayed response. @dav3r you are correct that I just want to make the latest version of cobalt strike gets installed on the Kali and teamserver images. I wasn't sure what method was used for ensuring the latest version of CS was on the systems. Based on what @mcdonnnj was saying it sounds like this won't be a problem since the latest version is downloaded from the website directly and installed each time the environments are deployed. If that's the case then we are good and you can close this ticket.

**Comment by jsf9k** [comment]
> ...it sounds like this won't be a problem since the latest version is downloaded from the website directly and installed each time the environments are deployed. If that's the case then we are good and you can close this ticket.

That is true, but we use `expect` to handle the installer prompts and they have changed with 4.6.  I'm working on fixing that in #55.
